### PR TITLE
Add dev tools

### PR DESCRIPTION
**Pull request by cameronbaney**
# Description

The purpose of this PR is to add the following dev tools to the project:
- ESLint
- Prettier

I did so by following the guides [on the official Development Tools page](https://nuxtjs.org/guide/development-tools#eslint-and-prettier). I have my opinions on Prettier, and it seems like there are some rules that don't play nicely with Vue's style guides. What are you opinions on this? As of right now, there are some breaking rules until we disable some rules, mainly the rule about requiring an empty space before a self closing tag:

What we want:
`<hr>`

What Prettier wants:
`<hr />`

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

1. Run `yarn lint` in the repo to lint the code. There are some errors, but see above for the discussion about them.
2. Run the app locally with `yarn dev` and functionality for still work.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added unit tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by mahamzayed** [comment]
I personally think we should disable the rules in Prettier that don't conform to VueJS standards. At the end of the day, Prettier is just a code formatter and if we're mainly going to be using Vue I think it's better practice to stick to their rules.

**Comment by mahamzayed** [comment]
@cameronbaney If you have a chance to pair, I'm running into an issue with yarn:

```
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.62.dylib
  Referenced from: /usr/local/bin/node
  Reason: image not found
zsh: abort      yarn lint
```

**Comment by cameronbaney** [comment]
@mahamzayed I agree with that, and can disable those Prettier rules that conflict.

**Comment by cameronbaney** [comment]
@mahamzayed I forgot the bad news: As of right now, Prettier recommends disabling ESLint rules that conflict with Prettier, so we would have to tweak the Vue rule. 

https://github.com/prettier/prettier/issues/5246

The tweak I am going to add is to enforce self-closing tags on `void` elements, such as an `hr` or `img`. This will resolve the conflicts between the Prettier and ESLint https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/html-self-closing.md

**Comment by cameronbaney** [comment]
@mahamzayed I pushed up that change to the Vue rules to play nice with Prettier. We still have a few lint errors such as `warning  'v-html' directive can lead to XSS attack` and something with a test, but we will resolve these when rewriting these components.

**Pull request merged**
