### PR TITLE
Homepage #406rbf

### PR DESCRIPTION
**Pull request by cameronbaney**
# Description

The purpose of this PR is to add the redesigned homepage to the site. This is featuring placeholder copy for now, and it is not connected to contentful. I will work with @jwagenaar to figure out what contentful copy to pull in and address that in a separate PR.

## Large viewport
localhost_3000_(Laptop with HiDPI screen)

## Extra small viewport
localhost_3000_(iPhone X)

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

This has been tested and verified in all of our supported browsers. In addition, I have went through various viewport sizes and made the extra small and large viewports match the designs.

- Run the app with `yarn dev`
- View the homepage in multiple browsers and viewports

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by cameronbaney** [comment]
Closing to address grid.

**Comment by cameronbaney** [comment]
I fixed the grid alignment on the homepage, and we can revisit the grid when we get into the subpages of the site.

**Comment by smith-annelise** [comment]
@cameronbaney Hey Cameron, I spent some time on Friday to refine the [visual design](https://share.goabstract.com/c0366e0b-3076-4977-ab0d-937838af0428?collectionLayerId=03953d52-b36d-46c2-94be-d7ecc7df4fe4&mode=design) of this page. 
Some notes:
- I realized that I had some incorrect button styling in my original wireframe, fixed that to match the element style guide Crys created last year
- Is it possible to do a header and body copy in that initial purple overview section? 
- Is it possible to control the styling of the Twitter feed any more than we are now? If not, I am thinking that section could go on a white background. 
- I updated the site section headers to medium (not bold)
- I think the explore dataset by category section will only need 5 categories, but we can wait on this because they still haven't been determined. Once they are I can provide the final icons. But I realized we could use labels for them, is that possible with live type under the icons?
- Changed color styling for testimonial section

Let me know if you have any questions! Thank you!

**Comment by cameronbaney** [comment]
@smith-annelise Thanks, I have created a new subtask and added this to the description. https://app.clickup.com/t/447d9t

We can do a header and body copy. I can add the appropriate fields to the CMS.

There are [limited options](https://developer.twitter.com/en/docs/twitter-for-websites/webpage-properties/overview) for customizing the style of the Twitter feed when using the Twitter embed. We can opt for something more custom, which is what is currently on the site, but I would suggest doing that as an enhancement after launch.

**Pull request merged**
